@echo off
echo Checking if application is running...
tasklist /FI "IMAGENAME eq vpnui.exe" 2>NUL | find /I /N "vpnui.exe">NUL
if "%ERRORLEVEL%"=="0" echo AnyConnect is running...
taskkill /F /IM vpnui.exe /T

echo Checking if application is running...
tasklist /FI "IMAGENAME eq vpnui.exe" 2>NUL | find /I /N "vpnui.exe">NUL
if "%ERRORLEVEL%"=="0" echo AnyConnect is running...